name: CI

on:
  workflow_dispatch:
  push:
    branches:
    - master
    tags:
    - v*

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      FEEDZ_LITTLEFORKER_API_KEY: ${{secrets.FEEDZ_LITTLEFORKER_API_KEY}}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build and Test
      run: bash build.sh
      shell: bash
      timeout-minutes: 5
